name: CI & Release

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint check
        run: npm run lint:check

      - name: Format check
        run: npm run format:check

      - name: Build
        run: npm run build

  build-macos:
    name: Build macOS App
    needs: test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Package macOS App
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "Publishing build because this is a tag."
            npm run dist:mac
          else
            echo "Building without publishing (not a tag)."
            npm run build
          fi
        env:
          # GitHub token for publishing releases
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Apple Developer credentials for notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
          # Code signing certificate (base64 encoded .p12 file)
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist
          path: |
            release/*.dmg
            release/*.zip
            release/latest-mac.yml

  release:
    name: Publish to GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-macos
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-dist
          path: ./dist

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            ./dist/*.dmg
            ./dist/*.zip
            ./dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
