name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-macos:
    name: Build and Release macOS
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Sign macOS App
        run: npm run package:publish
        env:
          # GitHub token for publishing releases
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Apple Developer credentials for notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
          # Code signing certificate (base64 encoded .p12 file)
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: |
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
          retention-days: 90

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
          draft: false
          prerelease: false
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 